[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["pip install --break-system-packages -r requirements.txt"]

[start]
cmd = "python3 bot.py"
[phases.setup]
nixPkgs = ["python311", "gcc", "ffmpeg"]
