[phases.setup]
nixPkgs = ["python311", "gcc", "ffmpeg", "deno"]

[phases.install]
cmds = ["pip install --break-system-packages -r requirements.txt"]

[start]
cmd = "yt-dlp -U || true; python3 bot.py"
